version: '3.4'

services:
  pollr.adminui:
    image: ${DOCKER_REGISTRY-}pollradminui
    build:
      context: .
      dockerfile: Pollr.AdminUI/Dockerfile

  pollr.api:
    image: ${DOCKER_REGISTRY-}pollrapi
    build:
      context: .
      dockerfile: Pollr.API/Dockerfile


  pollr.ui:
    image: ${DOCKER_REGISTRY-}pollrui
    build:
      context: .
      dockerfile: Pollr.UI/Dockerfile

