version: '3.4'

services:
  pollr.adminui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  pollr.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  pollr.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

