version: '3.4'

services:
  pollr.api:
    image: ${DOCKER_REGISTRY-}pollrapi
    build:
      context: .
      dockerfile: Pollr.API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PollrDatabase=${POLLR_DATABASE}


  pollr.ui:
    image: ${DOCKER_REGISTRY-}pollrui
    build:
      context: .
      dockerfile: Pollr.UI/Dockerfile
    ports: 
      - "81:80"
    environment:
      - ClientConfiguration__ApiUrl=${API_URL}
      - ClientConfiguration__HubUrl=${HUB_URL}
      - ASPNETCORE_ENVIRONMENT=production

    depends_on:
      - "pollr.api"

  pollr.adminui:
    image: ${DOCKER_REGISTRY-}pollradminui
    build:
      context: .
      dockerfile: Pollr.AdminUI/Dockerfile
    ports: 
      - "82:80"
    environment:
      - ClientConfiguration__ApiUrl=${API_URL}
      - ClientConfiguration__HubUrl=${HUB_URL}
      - ClientConfiguration__VoteUrl=${VOTE_URL}
      - ASPNETCORE_ENVIRONMENT=production

    depends_on:
      - "pollr.api"